### PR TITLE
Async

### LINKED ISSUE #2: avoid callback
Hello, I'm here again. 

Actually I was trying to find out 'what will happen when the primary key get duplicate' but haven't caught any exceptions. So I dived into your code and fount that all the `JSException`s are caught there and the `ActionCompleted` event was raised. This confused me a lot since there seems to be no reason to do that, and both you and the users will find it inconvenient to deal with the event and the transactions.

Well, later when I found that all the js functions are returning nothing in direct but just using `.then` and `.catch`, I think I understand all of that. However, Blazor JavaScript interop could directly deal with promises:

```javascript
// js part
window.func = function (doReject)
{
    return new Promise(
        (resolve, reject) => setTimeout(() =>
        {
            if (doReject)
                reject("Task Failed");
            else
                resolve("Task Completed Successfully");
        }, 1000));
}
```

```csharp
        // c# part
        var result = await js.InvokeAsync<string>("func", false);
        logger.LogInformation(result);
        // Output: Task Completed Successfully

        try
        {
            await js.InvokeAsync<string>("func", true);
        }
        catch(JSException e)
        {
            logger.LogError(e.Message);
            // Output: Task Failed
        }
```

Meanwhile, an async js method might be a better choice:

```javascript
window.delay = function (ms)
{
    return new Promise(resolve => setTimeout(resolve, ms));
}

window.func = async function (doReject)
{
    await delay(1000);
    if (doReject)
        throw "Task Failed";
    return "Task Completed Successfully";
}
```

And `CancellationTokenSource`s are even able to be used to cancel the promises: [Abort a long-running JavaScript function](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0#abort-a-long-running-javascript-function)

So my suggestion is to avoid using callbacks but to use the above measures instead. Hope you won't hate me this time, since it will be a really great change to the whole project. Of course, it's just a suggestion and the choice is yours.

### PR DESCRIPTION
**Pull request by yueyinqiu**
fixes #2

In this PR I will try to replace the event callback style with async style.

### CODE REVIEW

**Comment by yueyinqiu** [comment]
As an example, I have just modified `OpenDb` to `OpenDbAsync`. Maybe you shall check it before more works are done? @magiccodingman

**Comment by magiccodingman** [comment]
Thank you! Let me review this @yueyinqiu . I've been really busy recently, but I appreciate the  PR's! I'll check out your other one shortly as well :)

**Review by magiccodingman — APPROVED** [review]

**Comment by magiccodingman** [comment]
I finally had a moment to check out the PR and review! Thank you for contributing!

**Comment by yueyinqiu** [comment]
Wow! But I think this PR is not ready... All the methods shall be convert to async. And I just convert one of them as an example currently.

Anyway, if you don't decide to make other changes and publish a new version, it will be fine. I will work on other methods as soon as possible.

**Pull request merged**
